### ISSUE TITLE
Differences to the original OECD SAF-T 2.0 schema

### ISSUE THREAD

**Issue by kidahl** [Skatteetaten/saf-t#18]
I am trying to identify the changes the Norwegian spec has made to the original SAF-T 2.0 schema. However, I am unable to find _any_ source for the actual OECD SAF-T 2.0 XSD outside of an XMLSply generated PDF (https://www.oecd.org/tax/administration/45167181.pdf).

Could you please point me to the original OECD SAF-T 2.0 XSD that this standard is based on?

**Comment by steinarberggren** [comment]
On page 8 in the technical description the principal changes is explained by use of colors. New, not in use, and changed elements. The OECD SAF-T 2.0 XSD can be found on this page: 

https://www.skatteetaten.no/bedrift-og-organisasjon/starte-og-drive/rutiner-regnskap-og-kassasystem/saf-t-regnskap/dokumentasjon/

Downloading the SAF-T report to the Ministry of Finance in a ZIP following the link on this page "SAF-T Rapporten" or the one below: 

https://www.skatteetaten.no/globalassets/bedrift-og-organisasjon/starte-og-drive/rutiner-regnskap-og-kassasystem/saf-t-regnskap/saf-trapport2014finansdepartementet.zip

**Comment by kidahl** [comment]
Thank you, Steinar. 
It seems to me that the Norwegian version of the schema has removed the possibility of extending the schema using namespaces. For example, the OECD AuditFile headerstructure has
~~~~
<xs:any namespace="##other" minOccurs="0">
   <xs:annotation>
      <xs:documentation>Represents space to allow individual Revenue Bodies to add further elements if required. See Annex A.</xs:documentation>
   </xs:annotation>
</xs:any>
~~~~

This allows me to define my own schema with a custom namespace and insert my elements where the ANY declaration allows. All this without breaking the original schema compliance. In theory, much of the Norwegian adaptation probably could be implemented this way (I'm not saying that would be the correct approach for the Norwegian adaptation, but the namespace extension mechanism is pretty powerful.)

If I understand this correctly, further extensions with a custom namespace for a particular domain based on the unmodified Norwegian XSD will be impossible.

Would you reconsider removing the XS:ANY extensions from the Norwegian standard? Or do you recommend another approach to add custom information and still be compliant with the Norwegian spec?
